all:

	g++ FluxMap_withMagneticField.cc -o FluxMap_withMagneticField -Wfatal-errors -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ FluxMap_withoutMagneticField.cc -o FluxMap_withoutMagneticField -Wfatal-errors -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
