all:

	g++ Position_plots.cc -o Position_plots -Wfatal-errors -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ Vertex_plots.cc -o Vertex_plots -Wfatal-errors -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ Theta_energy_plots_ONLY_ELEPOSI.cc -o Theta_energy_plots_ONLY_ELEPOSI -Wfatal-errors -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ Analyse_first_Theta_peak.cc -o Analyse_first_Theta_peak -Wfatal-errors -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
