all:

	g++ Drawing_bremsstrahlung_Spectrum.cc -o Drawing_bremsstrahlung_Spectrum -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ Drawing_bremsstrahlung_Spectrum_single_rootfiles.cc -o Drawing_bremsstrahlung_Spectrum_single_rootfiles -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ Drawing_bremsstrahlung_Spectrum_TChain.cc -o Drawing_bremsstrahlung_Spectrum_TChain -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
