all:

	g++ DrawHistograms_Momentum_Energy_LeadBlock_20_40cm.cc -o DrawHistograms_Momentum_Energy_LeadBlock_20_40cm -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ DrawHistograms_Momentum_Energy_LeadBlock_20cm_PMMA_5cm.cc -o DrawHistograms_Momentum_Energy_LeadBlock_20cm_PMMA_5cm -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ DrawHistograms_Momentum_Energy_LeadBlock_20cm_Concrete_20cm.cc -o DrawHistograms_Momentum_Energy_LeadBlock_20cm_Concrete_20cm -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ DrawHistograms_LeadBlock_20cm_Concrete20cm_VS_PMMA5cm.cc -o DrawHistograms_LeadBlock_20cm_Concrete20cm_VS_PMMA5cm -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
