all:

	g++ DrawHistograms_comparison_w_wo_pipe.cc -o DrawHistograms_comparison_w_wo_pipe -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
