all:

	g++ DrawHistograms_Position_Energy_LeadBlock.cc -o DrawHistograms_Position_Energy_LeadBlock -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
