all:

	g++ MergeNSkim.cc -o MergeNSkim -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ DrawHistograms_comparison_w_wo_air.cc -o DrawHistograms_comparison_w_wo_air -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
