all:

	g++ DrawHistos_Pipe_LeadShielding.cc -o DrawHistos_Pipe_LeadShielding -Wfatal-errors -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
