all:

	g++ DrawHistograms_DeflectionAngle_MagneticField.cc -o DrawHistograms_DeflectionAngle_MagneticField -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ DrawHistograms_DeflectionAngle_MagneticField_DifferentEnergies.cc -o DrawHistograms_DeflectionAngle_MagneticField_DifferentEnergies -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
