all:

	g++ DrawHistograms_Magnet_wo_Collimator.cc -o DrawHistograms_Magnet_wo_Collimator -Wfatal-errors -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
	g++ Analyse_first_Theta_peak.cc -o Analyse_first_Theta_peak -Wfatal-errors -I /nfs/dust/atlas/user/schuea/scratch/sid_complete/v01-17-02-sid/root/5.34.05/include `root-config --cflags --glibs`
